# Generated by Django 5.2.11 on 2026-03-01 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_institute_delete_instituteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='register_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='year_of_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
