# Generated by Django 5.2.11 on 2026-03-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_certificate_blockchain_tx_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('register_number', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('certificate_file', models.FileField(upload_to='institute_certificates/')),
                ('certificate_hash', models.CharField(max_length=64, unique=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
