# Generated by Django 5.2.11 on 2026-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_institutecertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='authorization_file',
        ),
        migrations.AddField(
            model_name='institute',
            name='provided_courses',
            field=models.TextField(default='Not specified', help_text='Example: Python, Data Science, 3 Month Diploma, 1 Year Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='signature',
            field=models.ImageField(default='default.png', upload_to='signatures/'),
            preserve_default=False,
        ),
    ]
