import io
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import FastAPI
from sqlalchemy import func, select
from sqlalchemy.orm import Session

# ReportLab PDF Generation
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.code_chunk import CodeChunk
from app.models.project import Project
from app.models.user import User
from app.schemas.function_doc import FunctionDocRequest
from app.services.api_documentation_service import api_documentation_service
from app.services.function_doc_service import function_doc_service
from app.services.project_service import (
    analyze_project,
    analyze_project_dependencies,
    get_project_file_tree,
)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas for dynamic total page counting ("Page X of Y"),
    running top header, and running bottom footer across all pages.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Top running header (omitted on page 1 if desired, but consistent throughout)
        self.drawString(54, 11 * inch - 36, "CodeSage AI — Automated Technical Documentation")
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 11 * inch - 42, 8.5 * inch - 54, 11 * inch - 42)

        # Bottom running footer
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 54, 36, page_str)
        self.drawString(54, 36, "Confidential — Generated by CodeSage AI Platform")
        self.line(54, 46, 8.5 * inch - 54, 46)

        self.restoreState()


class ExportService:
    """
    Export Service for CodeSage AI (Day 22).
    Generates professional, publication-quality Markdown (.md) and PDF (.pdf)
    exports for projects, individual functions, and API specifications.
    """

    # =========================================================================
    # HELPERS
    # =========================================================================

    def _format_size(self, bytes_val: Optional[int]) -> str:
        """Formats byte counts into human-readable strings."""
        if not bytes_val and bytes_val != 0:
            return "0 B"
        if bytes_val < 1024:
            return f"{bytes_val} B"
        if bytes_val < 1024 * 1024:
            return f"{bytes_val / 1024:.1f} KB"
        return f"{bytes_val / (1024 * 1024):.2f} MB"

    def _build_ascii_tree(self, node: Dict[str, Any], prefix: str = "", max_depth: int = 5, current_depth: int = 0) -> List[str]:
        """Recursively formats folder hierarchy into clean ASCII directory tree."""
        if current_depth > max_depth:
            return [prefix + "... (truncated)"]

        lines = []
        children = node.get("children", [])
        total_children = len(children)

        for i, child in enumerate(children):
            is_last = (i == total_children - 1)
            connector = "└── " if is_last else "├── "
            child_prefix = "    " if is_last else "│   "

            name = child.get("name", "unnamed")
            if child.get("type") == "folder":
                lines.append(f"{prefix}{connector}{name}/")
                lines.extend(self._build_ascii_tree(child, prefix + child_prefix, max_depth, current_depth + 1))
            else:
                lines.append(f"{prefix}{connector}{name}")

        return lines

    def _get_project_functions(self, db: Session, project_id: int) -> List[CodeChunk]:
        """Queries stored function and method code chunks for project."""
        stmt = (
            select(CodeChunk)
            .where(
                CodeChunk.project_id == project_id,
                CodeChunk.symbol_type.in_(["function", "method"]),
            )
            .order_by(CodeChunk.file_path, CodeChunk.start_line)
            .limit(100)
        )
        return list(db.scalars(stmt).all())

    # =========================================================================
    # 1. PROJECT DOCUMENTATION EXPORT (MARKDOWN)
    # =========================================================================

    def generate_project_markdown(self, db: Session, project: Project) -> str:
        """
        Compiles a comprehensive technical Markdown report for an uploaded project.
        """
        analysis = analyze_project(db, project.id, project.user_id)
        dependencies = analyze_project_dependencies(db, project.id, project.user_id)
        functions = self._get_project_functions(db, project.id)

        stats = analysis.statistics
        owner_name = project.user.name if project.user else "CodeSage User"
        owner_email = project.user.email if project.user else "user@codesage.ai"
        created_str = project.created_at.strftime("%Y-%m-%d %H:%M UTC") if project.created_at else "N/A"

        md = []
        # Title
        md.append(f"# {project.name} — Project Documentation Report\n")
        md.append(f"> Generated automatically by **CodeSage AI** on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}.\n")
        md.append("---\n")

        # Table of Contents
        md.append("## Table of Contents\n")
        md.append("1. [Project Overview](#project-overview)")
        md.append("2. [System Statistics & Diagnostics](#system-statistics--diagnostics)")
        md.append("3. [Programming Language Distribution](#programming-language-distribution)")
        md.append("4. [Architecture & Dependencies](#architecture--dependencies)")
        md.append("5. [Project Directory Hierarchy](#project-directory-hierarchy)")
        md.append("6. [Functions & Methods Catalog](#functions--methods-catalog)")
        md.append("7. [Source File Manifest](#source-file-manifest)\n")
        md.append("---\n")

        # 1. Project Overview
        md.append("## Project Overview\n")
        md.append("| Property | Detail |")
        md.append("| :--- | :--- |")
        md.append(f"| **Project Name** | `{project.name}` |")
        md.append(f"| **Description** | {project.description or 'No description provided.'} |")
        md.append(f"| **Primary Language** | {project.programming_language or 'Auto-detected'} |")
        md.append(f"| **Framework** | {project.framework or 'General / Modular'} |")
        md.append(f"| **Original Archive** | `{project.original_filename or 'upload.zip'}` |")
        md.append(f"| **Created At** | {created_str} |")
        md.append(f"| **Project Owner** | {owner_name} (`{owner_email}`) |")
        md.append(f"| **Status** | `{project.status}` |\n")

        # 2. System Statistics & Diagnostics
        loc = project.lines_of_code or 0
        md.append("## System Statistics & Diagnostics\n")
        md.append("| Metric | Measured Value |")
        md.append("| :--- | :--- |")
        md.append(f"| **Total Source Files** | {stats.total_files:,} files |")
        md.append(f"| **Total Folders** | {stats.total_folders:,} folders |")
        md.append(f"| **Total Lines of Code** | {loc:,} lines |")
        md.append(f"| **Total Project Size** | {self._format_size(stats.total_size_bytes)} |")
        md.append(f"| **Indexed Code Chunks** | {len(project.code_chunks):,} chunks |\n")

        # 3. Programming Language Distribution
        md.append("## Programming Language Distribution\n")
        if analysis.languages:
            md.append("| Language | File Count | Share |")
            md.append("| :--- | :--- | :--- |")
            for lang, count in sorted(analysis.languages.items(), key=lambda x: x[1], reverse=True):
                pct = (count / stats.total_files * 100) if stats.total_files > 0 else 0
                md.append(f"| **{lang}** | {count} | {pct:.1f}% |")
            md.append("")
        else:
            md.append("*No recognized programming languages detected.*\n")

        # 4. Architecture & Dependencies
        md.append("## Architecture & Dependencies\n")
        manifests = sorted(list({p.source for p in dependencies.packages if p.source}))
        if manifests:
            md.append(f"**Manifest Files Detected**: {', '.join([f'`{m}`' for m in manifests])}\n")
        if dependencies.packages:
            md.append(f"**Direct External Dependencies ({len(dependencies.packages)})**:\n")
            for pkg in dependencies.packages:
                ver_str = f" (`{pkg.version}`)" if pkg.version else ""
                md.append(f"- **{pkg.name}**{ver_str} — {pkg.type or 'dependency'}")
            md.append("")
        else:
            md.append("*No external package manifests detected or project is standalone.*\n")

        # 5. Project Directory Hierarchy
        md.append("## Project Directory Hierarchy\n")
        md.append("```text")
        md.append(f"{project.name}/")
        if analysis.folder_hierarchy:
            tree_lines = self._build_ascii_tree(analysis.folder_hierarchy.model_dump())
            md.extend(tree_lines[:80])
            if len(tree_lines) > 80:
                md.append("... (tree truncated for export readability)")
        md.append("```\n")

        # 6. Functions & Methods Catalog
        md.append("## Functions & Methods Catalog\n")
        if functions:
            md.append(f"Discovered **{len(functions)}** function/method chunks across project source files:\n")
            md.append("| Symbol | Enclosing Class | File Path | Line Span |")
            md.append("| :--- | :--- | :--- | :--- |")
            for fn in functions[:60]:
                parent = f"`{fn.parent_symbol}`" if fn.parent_symbol else "—"
                md.append(f"| `{fn.symbol_name}` | {parent} | `{fn.file_path}` | Lines {fn.start_line}–{fn.end_line} |")
            if len(functions) > 60:
                md.append(f"\n*(Showing 60 of {len(functions)} functions)*\n")
            md.append("")
        else:
            md.append("*No functions currently indexed. Run 'Index Code' in Project Overview to discover functions.*\n")

        # Footer Notice
        md.append("---\n")
        md.append("*Document produced by CodeSage AI Platform. Grounded strictly in actual source code definitions.*")

        return "\n".join(md)

    # =========================================================================
    # 2. PROJECT DOCUMENTATION EXPORT (PDF)
    # =========================================================================

    def generate_project_pdf(self, db: Session, project: Project) -> bytes:
        """
        Generates a styled, publication-ready PDF document for an uploaded project.
        """
        analysis = analyze_project(db, project.id, project.user_id)
        dependencies = analyze_project_dependencies(db, project.id, project.user_id)
        functions = self._get_project_functions(db, project.id)

        stats = analysis.statistics
        owner_name = project.user.name if project.user else "CodeSage User"
        owner_email = project.user.email if project.user else "user@codesage.ai"
        created_str = project.created_at.strftime("%Y-%m-%d %H:%M UTC") if project.created_at else "N/A"

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
            title=f"CodeSage AI - {project.name} Documentation",
            author="CodeSage AI",
        )

        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1e1b4b"),
            spaceAfter=6,
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=14,
            fontName="Helvetica",
        )
        h1_style = ParagraphStyle(
            "Heading1_Custom",
            parent=styles["Heading2"],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#0f172a"),
            spaceBefore=14,
            spaceAfter=8,
            fontName="Helvetica-Bold",
        )
        body_style = ParagraphStyle(
            "Body_Custom",
            parent=styles["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
            fontName="Helvetica",
        )
        code_style = ParagraphStyle(
            "Code_Custom",
            parent=styles["Code"],
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#0f172a"),
            fontName="Courier",
        )
        table_cell_bold = ParagraphStyle(
            "CellBold",
            parent=styles["Normal"],
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#0f172a"),
            fontName="Helvetica-Bold",
        )
        table_cell_val = ParagraphStyle(
            "CellVal",
            parent=styles["Normal"],
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#334155"),
            fontName="Helvetica",
        )

        story = []

        # Document Header
        story.append(Paragraph(f"{project.name}", title_style))
        story.append(Paragraph(f"CodeSage AI Automated Technical Report &bull; Generated {datetime.utcnow().strftime('%B %d, %Y')}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceBefore=0, spaceAfter=14))

        # 1. Project Overview
        story.append(Paragraph("1. Project Overview", h1_style))
        overview_data = [
            [Paragraph("Project Name", table_cell_bold), Paragraph(project.name, table_cell_val)],
            [Paragraph("Description", table_cell_bold), Paragraph(project.description or "No description provided.", table_cell_val)],
            [Paragraph("Primary Language", table_cell_bold), Paragraph(project.programming_language or "Auto-detected", table_cell_val)],
            [Paragraph("Framework", table_cell_bold), Paragraph(project.framework or "General / Modular", table_cell_val)],
            [Paragraph("Original File", table_cell_bold), Paragraph(project.original_filename or "upload.zip", table_cell_val)],
            [Paragraph("Created", table_cell_bold), Paragraph(created_str, table_cell_val)],
            [Paragraph("Project Owner", table_cell_bold), Paragraph(f"{owner_name} ({owner_email})", table_cell_val)],
        ]
        t_overview = Table(overview_data, colWidths=[1.8 * inch, 5.2 * inch])
        t_overview.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#f8fafc")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(t_overview)
        story.append(Spacer(1, 14))

        # 2. System Diagnostics & Statistics
        story.append(Paragraph("2. System Diagnostics & Statistics", h1_style))
        loc = project.lines_of_code or 0
        stats_data = [
            [Paragraph("Total Source Files", table_cell_bold), Paragraph(f"{stats.total_files:,}", table_cell_val),
             Paragraph("Total Folders", table_cell_bold), Paragraph(f"{stats.total_folders:,}", table_cell_val)],
            [Paragraph("Lines of Code", table_cell_bold), Paragraph(f"{loc:,}", table_cell_val),
             Paragraph("Total Project Size", table_cell_bold), Paragraph(self._format_size(stats.total_size_bytes), table_cell_val)],
            [Paragraph("Code Chunks Indexed", table_cell_bold), Paragraph(f"{len(project.code_chunks):,}", table_cell_val),
             Paragraph("Project Status", table_cell_bold), Paragraph(project.status.capitalize(), table_cell_val)],
        ]
        t_stats = Table(stats_data, colWidths=[1.8 * inch, 1.7 * inch, 1.8 * inch, 1.7 * inch])
        t_stats.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#f8fafc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(t_stats)
        story.append(Spacer(1, 14))

        # 3. Programming Language Breakdown
        story.append(Paragraph("3. Programming Language Distribution", h1_style))
        if analysis.languages:
            lang_data = [[Paragraph("Language", table_cell_bold), Paragraph("Files", table_cell_bold), Paragraph("Percentage", table_cell_bold)]]
            for lang, count in sorted(analysis.languages.items(), key=lambda x: x[1], reverse=True):
                pct = (count / stats.total_files * 100) if stats.total_files > 0 else 0
                lang_data.append([
                    Paragraph(lang, table_cell_val),
                    Paragraph(str(count), table_cell_val),
                    Paragraph(f"{pct:.1f}%", table_cell_val),
                ])
            t_lang = Table(lang_data, colWidths=[2.5 * inch, 2.2 * inch, 2.3 * inch])
            t_lang.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(t_lang)
        else:
            story.append(Paragraph("No language distribution data recorded.", body_style))
        story.append(Spacer(1, 14))

        # 4. Architecture & Dependencies
        manifest_files = sorted(list({p.source for p in dependencies.packages if p.source}))
        if dependencies.packages or manifest_files:
            story.append(Paragraph("4. Architecture & Dependencies", h1_style))
            if manifest_files:
                manifest_str = ", ".join(manifest_files)
                story.append(Paragraph(f"<b>Manifest Files:</b> {manifest_str}", body_style))
                story.append(Spacer(1, 6))

            if dependencies.packages:
                dep_data = [[Paragraph("Package", table_cell_bold), Paragraph("Version", table_cell_bold), Paragraph("Type / Scope", table_cell_bold)]]
                for p in dependencies.packages[:25]:
                    dep_data.append([
                        Paragraph(p.name, table_cell_val),
                        Paragraph(p.version or "latest", table_cell_val),
                        Paragraph(p.type or "dependency", table_cell_val),
                    ])
                t_dep = Table(dep_data, colWidths=[2.6 * inch, 2.0 * inch, 2.4 * inch])
                t_dep.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ]))
                story.append(t_dep)
            story.append(Spacer(1, 14))

        # 5. Functions Catalog (Page Break for clean presentation)
        if functions:
            story.append(PageBreak())
            story.append(Paragraph("5. Discovered Functions & Methods Catalog", h1_style))
            story.append(Paragraph(f"Displaying {min(len(functions), 40)} function symbols extracted via Tree-sitter AST parser:", body_style))
            story.append(Spacer(1, 8))

            fn_data = [[Paragraph("Symbol Name", table_cell_bold), Paragraph("Class", table_cell_bold), Paragraph("Source File", table_cell_bold), Paragraph("Lines", table_cell_bold)]]
            for fn in functions[:40]:
                fn_data.append([
                    Paragraph(f"<code>{fn.symbol_name}</code>", table_cell_val),
                    Paragraph(fn.parent_symbol or "—", table_cell_val),
                    Paragraph(fn.file_path, table_cell_val),
                    Paragraph(f"{fn.start_line}–{fn.end_line}", table_cell_val),
                ])
            t_fn = Table(fn_data, colWidths=[2.2 * inch, 1.4 * inch, 2.4 * inch, 1.0 * inch])
            t_fn.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(t_fn)

        # Build PDF using NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    # =========================================================================
    # 3. FUNCTION DOCUMENTATION EXPORT (MARKDOWN & PDF)
    # =========================================================================

    def generate_function_markdown(
        self, db: Session, project: Project, req: FunctionDocRequest
    ) -> str:
        """
        Exports individual function documentation as clean Markdown.
        """
        doc_res = function_doc_service.generate_function_doc(db, project, req)
        return doc_res.documentation

    def generate_function_pdf(
        self, db: Session, project: Project, req: FunctionDocRequest
    ) -> bytes:
        """
        Exports individual function documentation as a professional PDF.
        """
        doc_res = function_doc_service.generate_function_doc(db, project, req)

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
            title=f"CodeSage AI - {doc_res.function_name} Documentation",
            author="CodeSage AI",
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#1e1b4b"),
            spaceAfter=4,
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=12,
            fontName="Helvetica",
        )
        h2_style = ParagraphStyle(
            "Heading2_Custom",
            parent=styles["Heading2"],
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#0f172a"),
            spaceBefore=10,
            spaceAfter=4,
            fontName="Helvetica-Bold",
        )
        body_style = ParagraphStyle(
            "Body_Custom",
            parent=styles["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
            fontName="Helvetica",
        )
        table_cell_bold = ParagraphStyle("CellBold", parent=styles["Normal"], fontSize=8.5, leading=11, fontName="Helvetica-Bold")
        table_cell_val = ParagraphStyle("CellVal", parent=styles["Normal"], fontSize=8.5, leading=11, fontName="Helvetica")

        story = []

        # Function Title Banner
        story.append(Paragraph(f"Function: {doc_res.function_name}()", title_style))
        story.append(Paragraph(f"Project: {project.name} &bull; File: {doc_res.file_path} (Lines {doc_res.start_line}–{doc_res.end_line})", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceBefore=0, spaceAfter=10))

        # Purpose
        story.append(Paragraph("Purpose", h2_style))
        story.append(Paragraph(doc_res.purpose or "No purpose description available.", body_style))
        story.append(Spacer(1, 8))

        # Parameters
        story.append(Paragraph("Parameters", h2_style))
        if doc_res.parameters:
            param_data = [[Paragraph("Parameter", table_cell_bold), Paragraph("Type", table_cell_bold), Paragraph("Description", table_cell_bold)]]
            for p in doc_res.parameters:
                p_type = p.type or "Any"
                if p.default_value:
                    p_type += f" (default: {p.default_value})"
                param_data.append([
                    Paragraph(f"<code>{p.name}</code>", table_cell_val),
                    Paragraph(p_type, table_cell_val),
                    Paragraph(p.description or "—", table_cell_val),
                ])
            t_param = Table(param_data, colWidths=[1.8 * inch, 1.8 * inch, 3.4 * inch])
            t_param.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(t_param)
        else:
            story.append(Paragraph("None (Accepts no parameters).", body_style))
        story.append(Spacer(1, 8))

        # Returns
        story.append(Paragraph("Returns", h2_style))
        story.append(Paragraph(doc_res.returns or "None", body_style))
        story.append(Spacer(1, 8))

        # Behavior
        if doc_res.behavior:
            story.append(Paragraph("Execution Behavior", h2_style))
            for i, step in enumerate(doc_res.behavior, 1):
                story.append(Paragraph(f"<b>{i}.</b> {step}", body_style))
            story.append(Spacer(1, 8))

        # Important Logic
        if doc_res.logic:
            story.append(Paragraph("Important Logic & Branching", h2_style))
            for item in doc_res.logic:
                story.append(Paragraph(f"&bull; {item}", body_style))
            story.append(Spacer(1, 8))

        # Dependencies & Exceptions
        story.append(Paragraph("Dependencies & Exceptions", h2_style))
        dep_str = ", ".join(doc_res.dependencies) if doc_res.dependencies else "None"
        story.append(Paragraph(f"<b>Dependencies:</b> {dep_str}", body_style))
        err_str = ", ".join(doc_res.exceptions) if doc_res.exceptions else "None identifiable"
        story.append(Paragraph(f"<b>Exceptions:</b> {err_str}", body_style))
        story.append(Spacer(1, 10))

        # Source Code Snippet
        if doc_res.source_code:
            story.append(Paragraph("Source Code", h2_style))
            src_lines = doc_res.source_code.splitlines()[:35]
            story.append(Preformatted("\n".join(src_lines), styles["Code"]))

        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    # =========================================================================
    # 4. API DOCUMENTATION EXPORT (PDF)
    # =========================================================================

    def generate_api_docs_pdf(self, app: FastAPI) -> bytes:
        """
        Converts the Day 21 API Documentation catalog into an API Specification PDF.
        """
        catalog = api_documentation_service.discover_all_endpoints(app)

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
            title="CodeSage AI - API Specification Reference",
            author="CodeSage AI",
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle", parent=styles["Heading1"], fontSize=20, leading=24, textColor=colors.HexColor("#1e1b4b"), spaceAfter=4, fontName="Helvetica-Bold"
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle", parent=styles["Normal"], fontSize=9.5, leading=13, textColor=colors.HexColor("#64748b"), spaceAfter=14, fontName="Helvetica"
        )
        tag_style = ParagraphStyle(
            "TagHeading", parent=styles["Heading2"], fontSize=13, leading=17, textColor=colors.HexColor("#0284c7"), spaceBefore=12, spaceAfter=6, fontName="Helvetica-Bold"
        )
        table_cell_bold = ParagraphStyle("CellBold", parent=styles["Normal"], fontSize=8, leading=10, fontName="Helvetica-Bold")
        table_cell_val = ParagraphStyle("CellVal", parent=styles["Normal"], fontSize=8, leading=10, fontName="Helvetica")

        story = []

        story.append(Paragraph("CodeSage AI — API Specification Reference", title_style))
        story.append(Paragraph(f"Comprehensive FastAPI Catalog &bull; {catalog.total_endpoints} Endpoints &bull; Generated {datetime.utcnow().strftime('%B %d, %Y')}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceBefore=0, spaceAfter=12))

        # Group by tag
        by_tag: Dict[str, List[Any]] = {}
        for ep in catalog.endpoints:
            by_tag.setdefault(ep.tag, []).append(ep)

        for tag, endpoints in by_tag.items():
            story.append(Paragraph(f"Category: {tag}", tag_style))
            ep_data = [[Paragraph("Method", table_cell_bold), Paragraph("Endpoint Path", table_cell_bold), Paragraph("Auth", table_cell_bold), Paragraph("Summary", table_cell_bold)]]
            for ep in endpoints:
                auth_text = "Bearer JWT" if ep.auth_required else "Public"
                ep_data.append([
                    Paragraph(f"<b>{ep.method}</b>", table_cell_val),
                    Paragraph(f"<code>{ep.path}</code>", table_cell_val),
                    Paragraph(auth_text, table_cell_val),
                    Paragraph(ep.summary[:60] if ep.summary else "—", table_cell_val),
                ])
            t = Table(ep_data, colWidths=[0.8 * inch, 2.5 * inch, 1.1 * inch, 2.6 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes


export_service = ExportService()
