# Generated by Django 5.2.11 on 2026-03-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_enrollment_blockchain_tx_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='certificate_name',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='students.enrollment'),
        ),
    ]
