"""add_project_upload_fields

Revision ID: 93ffc5f36d82
Revises: df02727a1cce
Create Date: 2026-09-10 13:55:26.443141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ffc5f36d82'
down_revision: Union[str, Sequence[str], None] = 'df02727a1cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('storage_path', sa.String(length=1024), nullable=True))
    op.add_column('projects', sa.Column('extracted_path', sa.String(length=1024), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=50), server_default='uploaded', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'extracted_path')
    op.drop_column('projects', 'storage_path')
    op.drop_column('projects', 'original_filename')
    # ### end Alembic commands ###
