"""add embedding fields to code chunks

Revision ID: e72f629ad12e
Revises: 5ce1557671f6
Create Date: 2026-09-12 15:00:03.749796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72f629ad12e'
down_revision: Union[str, Sequence[str], None] = '5ce1557671f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_chunks', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('code_chunks', sa.Column('embedding_status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('code_chunks', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('code_chunks', sa.Column('embedded_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_chunks', 'embedded_hash')
    op.drop_column('code_chunks', 'embedding_dimension')
    op.drop_column('code_chunks', 'embedding_status')
    op.drop_column('code_chunks', 'embedding')
    # ### end Alembic commands ###
