from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict
from app.schemas.rag import RagSourceItem


class ChatRequest(BaseModel):
    """
    Request schema for Day 15 & Day 16 AI Chat (POST /api/projects/{project_id}/chat).
    """
    question: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Natural-language question about the project codebase",
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Number of relevant code chunks to retrieve from FAISS (1 to 10)",
    )
    conversation_id: Optional[int] = Field(
        default=None,
        description="Optional conversation session identifier. If omitted, a new conversation session is created.",
    )


class ChatResponse(BaseModel):
    """
    Response schema for Day 15 & Day 16 AI Chat (POST /api/projects/{project_id}/chat).
    """
    project_id: int = Field(..., description="Project identifier")
    conversation_id: Optional[int] = Field(None, description="Active conversation session ID")
    question: str = Field(..., description="User question asked")
    answer: str = Field(..., description="Grounded answer generated by Gemma via LangChain RAG")
    sources: List[RagSourceItem] = Field(
        default_factory=list,
        description="Retrieved source chunk citations from project code",
    )
    chat_id: Optional[int] = Field(None, description="Persisted chat history database record ID")
    created_at: Optional[datetime] = Field(None, description="Timestamp when the chat was recorded")
    model: str = Field(..., description="LLM model name used for generation")


class ChatHistoryItem(BaseModel):
    """
    Schema representing a stored conversation exchange in the project chat history.
    """
    id: int = Field(..., description="Chat record ID")
    project_id: int = Field(..., description="Project ID")
    user_id: int = Field(..., description="User ID")
    conversation_id: Optional[int] = Field(None, description="Conversation session ID")
    message: str = Field(..., description="User's question")
    response: str = Field(..., description="AI's generated response")
    created_at: datetime = Field(..., description="Creation timestamp")
    model_config = ConfigDict(from_attributes=True)

