"""
CodeSage AI — Day 20 Function Documentation Schemas
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class ParameterDoc(BaseModel):
    name: str
    type: Optional[str] = None
    description: Optional[str] = None
    default_value: Optional[str] = None


class FunctionDocRequest(BaseModel):
    file_path: str = Field(..., description="Project-relative path to the source file (e.g. app/services/auth.py)")
    function_name: str = Field(..., description="Name of the function or method to document")
    start_line: Optional[int] = Field(None, description="Optional 1-based start line of the function")
    end_line: Optional[int] = Field(None, description="Optional 1-based end line of the function")
    parent_class: Optional[str] = Field(None, description="Optional enclosing class name if method")


class FunctionDocItem(BaseModel):
    function_name: str
    type: str = "function"  # "function" or "method"
    file_path: str
    start_line: int
    end_line: int
    parent_class: Optional[str] = None
    language: str = "python"
    chunk_id: Optional[str] = None


class FunctionListResponse(BaseModel):
    project_id: int
    total_functions: int
    functions: List[FunctionDocItem] = Field(default_factory=list)


class FunctionDocResponse(BaseModel):
    project_id: int
    function_name: str
    file_path: str
    language: str
    start_line: int
    end_line: int
    parent_class: Optional[str] = None
    documentation: str  # Complete Markdown documentation generated by AI
    purpose: Optional[str] = None
    parameters: List[ParameterDoc] = Field(default_factory=list)
    returns: Optional[str] = None
    behavior: List[str] = Field(default_factory=list)
    logic: List[str] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list)
    exceptions: List[str] = Field(default_factory=list)
    usage_example: Optional[str] = None
    related_symbols: List[str] = Field(default_factory=list)
    source_code: str
