from typing import List, Optional
from pydantic import BaseModel, Field


class RagSourceItem(BaseModel):
    """
    Retrieved source code chunk citation returned with RAG answer (Phases 10, 15, 16, 30).
    """
    chunk_id: str = Field(..., description="Unique CodeSage chunk identifier")
    file_path: str = Field(..., description="Project-relative file path")
    file_name: str = Field(..., description="File basename")
    language: str = Field(..., description="Programming language")
    start_line: int = Field(..., description="1-indexed starting line number")
    end_line: int = Field(..., description="1-indexed ending line number")
    symbol_name: Optional[str] = Field(None, description="Function/class/method symbol name")
    symbol_type: Optional[str] = Field(None, description="Symbol type (function, class, module, etc.)")
    score: float = Field(..., description="Cosine similarity score from FAISS retrieval")


class RagRequest(BaseModel):
    """
    Request payload for POST /api/projects/{project_id}/rag (Phases 17, 18).
    """
    question: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Natural-language question about the project codebase"
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Number of relevant code chunks to retrieve from FAISS (1 to 10)"
    )


class RagResponse(BaseModel):
    """
    Response schema for POST /api/projects/{project_id}/rag (Phases 16, 17).
    """
    project_id: int = Field(..., description="Project identifier")
    question: str = Field(..., description="User question asked")
    answer: str = Field(..., description="Grounded answer generated by Gemma via LangChain")
    sources: List[RagSourceItem] = Field(..., description="Retrieved source chunk citations")
    model: str = Field(..., description="LLM model name used for generation")
