# Generated by Django 5.2.11 on 2026-02-28 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_instituteprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('institute_code', models.CharField(max_length=50, unique=True)),
                ('affiliation', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('established_year', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('admin_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('govt_reg_no', models.CharField(max_length=100, unique=True)),
                ('accreditation', models.CharField(max_length=100)),
                ('authorization_file', models.FileField(upload_to='authorization/')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InstituteProfile',
        ),
    ]
