# Generated by Django 5.2.11 on 2026-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='student_certificates/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_generated',
            field=models.BooleanField(default=False, help_text='Whether certificate has been generated'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained in the course', max_digits=5, null=True),
        ),
    ]
