# Generated by Django 5.2.11 on 2026-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrollment_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for certificate verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the certificate file for blockchain verification', max_length=64, null=True),
        ),
    ]
